// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DSS_SWP.Models;

public partial class Product
{
    public long Id { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public long MainDiamondId { get; set; }

    public string Image { get; set; }

    public long? ExtraDiamondId { get; set; }

    public long? NumberExDiamond { get; set; }

    public long? DiamondShellId { get; set; }

    public double? Size { get; set; }

    public double PriceRate { get; set; }

    public int Quantity { get; set; }

    public int Status { get; set; }

    public virtual DiamondShell DiamondShell { get; set; }

    public virtual ExtraDiamond ExtraDiamond { get; set; }

    public virtual MainDiamond MainDiamond { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<WarrantyCertificate> WarrantyCertificates { get; set; } = new List<WarrantyCertificate>();
}